package PayStation;


/**
* PayStation/PayStationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from pay.idl
* Thursday, 7 March 2019 11:50:50 o'clock GMT
*/

abstract public class PayStationHelper
{
  private static String  _id = "IDL:PayStation/PayStation:1.0";

  public static void insert (org.omg.CORBA.Any a, PayStation.PayStation that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PayStation.PayStation extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PayStation.PayStationHelper.id (), "PayStation");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PayStation.PayStation read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PayStationStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PayStation.PayStation value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PayStation.PayStation narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PayStation.PayStation)
      return (PayStation.PayStation)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PayStation._PayStationStub stub = new PayStation._PayStationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PayStation.PayStation unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PayStation.PayStation)
      return (PayStation.PayStation)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PayStation._PayStationStub stub = new PayStation._PayStationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
