package PayStation;


/**
* PayStation/PayStationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from pay.idl
* Thursday, 7 March 2019 11:50:50 o'clock GMT
*/

public interface PayStationOperations 
{
  String machine_name ();
  void register_station (String machine_name);
  void turn_on ();
  void turn_off ();
  void reset ();
  boolean check_vehicle (String registration);
  String pay (String registration, short duration);
  int return_cash_total ();
} // interface PayStationOperations
