package PayStation;


/**
* PayStation/PayStation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from pay.idl
* Thursday, 7 March 2019 12:20:55 o'clock GMT
*/

public interface PayStation extends PayStationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PayStation
