package PayStation;

/**
* PayStation/PayStationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from pay.idl
* Thursday, 7 March 2019 12:20:55 o'clock GMT
*/

public final class PayStationHolder implements org.omg.CORBA.portable.Streamable
{
  public PayStation.PayStation value = null;

  public PayStationHolder ()
  {
  }

  public PayStationHolder (PayStation.PayStation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PayStation.PayStationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PayStation.PayStationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PayStation.PayStationHelper.type ();
  }

}
