package CompanyHQ;

/**
* CompanyHQ/CompanyHQHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from headquarters.idl
* Thursday, 7 March 2019 12:20:43 o'clock GMT
*/

public final class CompanyHQHolder implements org.omg.CORBA.portable.Streamable
{
  public CompanyHQ.CompanyHQ value = null;

  public CompanyHQHolder ()
  {
  }

  public CompanyHQHolder (CompanyHQ.CompanyHQ initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CompanyHQ.CompanyHQHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CompanyHQ.CompanyHQHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CompanyHQ.CompanyHQHelper.type ();
  }

}
