package CompanyHQ;

/**
* CompanyHQ/VehicleEventHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from headquarters.idl
* Thursday, 7 March 2019 12:20:43 o'clock GMT
*/

public final class VehicleEventHolder implements org.omg.CORBA.portable.Streamable
{
  public CompanyHQ.VehicleEvent value = null;

  public VehicleEventHolder ()
  {
  }

  public VehicleEventHolder (CompanyHQ.VehicleEvent initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CompanyHQ.VehicleEventHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CompanyHQ.VehicleEventHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CompanyHQ.VehicleEventHelper.type ();
  }

}
