package LocalServer;


/**
* LocalServer/LocalServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Thursday, 7 March 2019 11:50:59 o'clock GMT
*/

public interface LocalServerOperations 
{
  String location ();
  LocalServer.VehicleEvent[] log ();
  void vehicle_in (LocalServer.VehicleEvent event);
  void vehicle_out (LocalServer.VehicleEvent event);
  boolean vehicle_in_car_park (String registration_number);
  int return_cash_total ();
  LocalServer.VehicleEvent[] return_log ();
  void add_entry_gate (String gate_name, String gate_ior);
  void add_exit_gate (String gate_name, String gate_ior);
  void add_pay_station (String station_name, String station_ior);
} // interface LocalServerOperations
