package LocalServer;

/**
* LocalServer/LocalServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Thursday, 7 March 2019 11:50:59 o'clock GMT
*/

public final class LocalServerHolder implements org.omg.CORBA.portable.Streamable
{
  public LocalServer.LocalServer value = null;

  public LocalServerHolder ()
  {
  }

  public LocalServerHolder (LocalServer.LocalServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LocalServer.LocalServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LocalServer.LocalServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LocalServer.LocalServerHelper.type ();
  }

}
