package CompanyHQ;


/**
* CompanyHQ/CompanyHQ.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from headquarters.idl
* Thursday, 7 March 2019 11:50:55 o'clock GMT
*/

public interface CompanyHQ extends CompanyHQOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CompanyHQ
