package CarPark;

/**
* CarPark/AlertsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Monday, 1 April 2019 11:19:23 o'clock BST
*/

public final class AlertsHolder implements org.omg.CORBA.portable.Streamable
{
  public CarPark.Alerts value = null;

  public AlertsHolder ()
  {
  }

  public AlertsHolder (CarPark.Alerts initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CarPark.AlertsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CarPark.AlertsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CarPark.AlertsHelper.type ();
  }

}
