package CarPark;


/**
* CarPark/Alerts.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
<<<<<<< HEAD
* Tuesday, 2 April 2019 22:49:29 o'clock BST
=======
* Tuesday, 2 April 2019 12:27:24 o'clock BST
>>>>>>> 4ffa59a92a35d3ac6659213456086bc70942bfc1
*/

public final class Alerts implements org.omg.CORBA.portable.IDLEntity
{
  public String alertType = null;
  public String overStayedBy = null;
  public String serverName = null;
  public CarPark.VehicleEvent vehicleEvent = null;

  public Alerts ()
  {
  } // ctor

  public Alerts (String _alertType, String _overStayedBy, String _serverName, CarPark.VehicleEvent _vehicleEvent)
  {
    alertType = _alertType;
    overStayedBy = _overStayedBy;
    serverName = _serverName;
    vehicleEvent = _vehicleEvent;
  } // ctor

} // class Alerts
