package CarPark;


/**
* CarPark/CompanyHQOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Tuesday, 26 March 2019 13:48:11 o'clock GMT
*/

public interface CompanyHQOperations 
{
  CarPark.LocalServers[] server_log ();
  void raise_alarm (CarPark.VehicleEvent event);
  void register_local_server (CarPark.LocalServers server);
  CarPark.Machines[] return_machines ();
} // interface CompanyHQOperations
