package CarPark;


/**
* CarPark/CompanyHQ.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Monday, 11 March 2019 12:35:47 o'clock GMT
*/

public interface CompanyHQ extends CompanyHQOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CompanyHQ
