package CarPark;


/**
* CarPark/CompanyHQ.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Sunday, 31 March 2019 09:48:09 o'clock BST
*/

public interface CompanyHQ extends CompanyHQOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CompanyHQ
