package CarPark;


/**
* CarPark/Date.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
<<<<<<< HEAD
* Tuesday, 2 April 2019 22:49:29 o'clock BST
=======
* Tuesday, 2 April 2019 12:27:24 o'clock BST
>>>>>>> 4ffa59a92a35d3ac6659213456086bc70942bfc1
*/

public final class Date implements org.omg.CORBA.portable.IDLEntity
{
  public int days = (int)0;
  public int months = (int)0;
  public int years = (int)0;

  public Date ()
  {
  } // ctor

  public Date (int _days, int _months, int _years)
  {
    days = _days;
    months = _months;
    years = _years;
  } // ctor

} // class Date
