package CarPark;


/**
* CarPark/EntryGateClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from entry.idl
* Thursday, 7 March 2019 12:48:12 o'clock GMT
*/

public interface EntryGate extends EntryGateOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EntryGateClient
