package CarPark;


/**
* CarPark/ExitGateOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Thursday, 28 March 2019 12:35:03 o'clock GMT
*/

public interface ExitGateOperations 
{
  String machine_name ();
  boolean status ();
  void register_gate (String machine_name, String ior);
  void turn_on ();
  void turn_off ();
  void reset ();
  void vehicle_exited (CarPark.Date date, CarPark.Time time, String registration);
} // interface ExitGateOperations
