package CarPark;


/**
* CarPark/ExitGateOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Saturday, 30 March 2019 18:35:23 o'clock GMT
*/

public interface ExitGateOperations 
{
  String machine_name ();
  boolean status ();
  void register_gate (String name, String ior, CarPark.LocalServer obj);
  String vehicle_exited (CarPark.Date date, CarPark.Time time, String registration);
  void turn_on (String machine_name, String machine_type);
  void turn_off (String machine_name, String machine_type);
  void reset (String machine_name, String machine_type);
} // interface ExitGateOperations
