package CarPark;


/**
* CarPark/ExitGateClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Monday, 25 March 2019 14:17:31 o'clock GMT
*/

public interface ExitGate extends ExitGateOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ExitGateClient
