package CarPark;


/**
* CarPark/LocalServers.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
<<<<<<< HEAD
* Tuesday, 2 April 2019 22:49:29 o'clock BST
=======
* Tuesday, 2 April 2019 12:27:24 o'clock BST
>>>>>>> 4ffa59a92a35d3ac6659213456086bc70942bfc1
*/

public final class LocalServers implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String ior = null;
  public CarPark.LocalServer obj = null;

  public LocalServers ()
  {
  } // ctor

  public LocalServers (String _name, String _ior, CarPark.LocalServer _obj)
  {
    name = _name;
    ior = _ior;
    obj = _obj;
  } // ctor

} // class LocalServers
