package CarPark;


/**
* CarPark/LocalServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Thursday, 7 March 2019 12:48:02 o'clock GMT
*/

public interface LocalServer extends LocalServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LocalServer
