package CarPark;


/**
* CarPark/LocalServersHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Monday, 1 April 2019 16:28:08 o'clock BST
*/

abstract public class LocalServersHelper
{
  private static String  _id = "IDL:CarPark/LocalServers:1.0";

  public static void insert (org.omg.CORBA.Any a, CarPark.LocalServers that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CarPark.LocalServers extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "ior",
            _tcOf_members0,
            null);
          _tcOf_members0 = CarPark.LocalServerHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "obj",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (CarPark.LocalServersHelper.id (), "LocalServers", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CarPark.LocalServers read (org.omg.CORBA.portable.InputStream istream)
  {
    CarPark.LocalServers value = new CarPark.LocalServers ();
    value.name = istream.read_string ();
    value.ior = istream.read_string ();
    value.obj = CarPark.LocalServerHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CarPark.LocalServers value)
  {
    ostream.write_string (value.name);
    ostream.write_string (value.ior);
    CarPark.LocalServerHelper.write (ostream, value.obj);
  }

}
