package CarPark;


/**
* CarPark/LocalServers.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Wednesday, 3 April 2019 13:51:54 o'clock BST
*/

public final class LocalServers implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String ior = null;
  public CarPark.LocalServer obj = null;

  public LocalServers ()
  {
  } // ctor

  public LocalServers (String _name, String _ior, CarPark.LocalServer _obj)
  {
    name = _name;
    ior = _ior;
    obj = _obj;
  } // ctor

} // class LocalServers
