package CarPark;


/**
* CarPark/LocalServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Wednesday, 3 April 2019 13:51:54 o'clock BST
*/

public interface LocalServer extends LocalServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LocalServer
