package CarPark;


/**
* CarPark/PayStation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
* Sunday, 31 March 2019 22:41:47 o'clock BST
*/

public interface PayStation extends PayStationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PayStation
