package CarPark;


/**
* CarPark/Time.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CarPark.idl
<<<<<<< HEAD
* Tuesday, 2 April 2019 22:49:29 o'clock BST
=======
* Tuesday, 2 April 2019 12:27:24 o'clock BST
>>>>>>> 4ffa59a92a35d3ac6659213456086bc70942bfc1
*/

public final class Time implements org.omg.CORBA.portable.IDLEntity
{
  public int seconds = (int)0;
  public int minutes = (int)0;
  public int hours = (int)0;

  public Time ()
  {
  } // ctor

  public Time (int _seconds, int _minutes, int _hours)
  {
    seconds = _seconds;
    minutes = _minutes;
    hours = _hours;
  } // ctor

} // class Time
