package EntryGate;


/**
* EntryGate/EntryGateHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from entry.idl
* Thursday, 7 March 2019 11:50:35 o'clock GMT
*/

abstract public class EntryGateHelper
{
  private static String  _id = "IDL:EntryGate/EntryGate:1.0";

  public static void insert (org.omg.CORBA.Any a, EntryGate.EntryGate that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EntryGate.EntryGate extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (EntryGate.EntryGateHelper.id (), "EntryGate");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EntryGate.EntryGate read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EntryGateStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EntryGate.EntryGate value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static EntryGate.EntryGate narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EntryGate.EntryGate)
      return (EntryGate.EntryGate)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EntryGate._EntryGateStub stub = new EntryGate._EntryGateStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static EntryGate.EntryGate unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EntryGate.EntryGate)
      return (EntryGate.EntryGate)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EntryGate._EntryGateStub stub = new EntryGate._EntryGateStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
