package ExitGate;


/**
* ExitGate/ExitGateOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exit.idl
* Thursday, 7 March 2019 11:50:45 o'clock GMT
*/

public interface ExitGateOperations 
{
  String machine_name ();
  void register_gate (String machine_name);
  void turn_on ();
  void turn_off ();
  void reset ();
  void vehicle_exited (int date, int time, String registration);
} // interface ExitGateOperations
