module CarPark {

    struct Date {
        long days;
        long months;
        long years;
    };

    struct Time {
        long seconds;
        long minutes;
        long hours;
    };

    struct VehicleEvent {
    	Time time;
    	Date date;
    	string registration_number;
    	short duration;
    	double cost;
    	string operation;
    };

    struct Machines {
        string machine_name;
        string machine_type;
        string ior;
        boolean enabled;
    };

    struct LocalServers {
        string location;
        string ior;
    };

    typedef sequence<VehicleEvent> Log_of_vehicle_events;
    typedef sequence<Machines> Log_of_machines;
    typedef sequence<LocalServers> Log_of_local_servers;

	interface EntryGate {
		readonly attribute string machine_name;
		void register_gate(in string machine_name, in string ior);
		void turn_on();
		void turn_off();
		void reset();
		void vehicle_entered(in Date date, in Time time, in string registration);
	};

	interface ExitGate {
    	readonly attribute string machine_name;
    	void register_gate(in string machine_name, in string ior);
    	void turn_on();
     	void turn_off();
     	void reset();
    	void vehicle_exited(in Date date, in Time time, in string registration);
    };

	interface PayStation {
    	readonly attribute string machine_name;
    	void register_station(in string machine_name, in string ior);
    	void turn_on();
     	void turn_off();
     	void reset();
    	boolean check_vehicle(in string registration);
    	boolean pay(in string registration, in Date datePaid, in Time timePaid, in short duration, in double cost);
    	double return_cash_total();
    };

    interface LocalServer {
    	readonly attribute string location;
    	readonly attribute Log_of_vehicle_events events_log;
    	readonly attribute Log_of_machines machine_log;
    	void register_server(in string location, in string ior);
    	void vehicle_in(in VehicleEvent event);
    	void vehicle_out(in VehicleEvent event);
    	boolean vehicle_pay(in VehicleEvent event);
    	boolean vehicle_paid_for(in string registration_number);
    	boolean vehicle_in_car_park(in string registration_number);
    	double return_cash_total();
    	Log_of_vehicle_events return_log();
        boolean change_entry_gate_state(in string machine_name, in boolean state);
        boolean change_exit_gate_state(in string machine_name, in boolean state);
        boolean change_pay_station_state(in string machine_name, in boolean state);
    	void add_entry_gate(in Machines machine);
    	void add_exit_gate(in Machines machine);
    	void add_pay_station(in Machines machine);
    };

    interface CompanyHQ {
        readonly attribute Log_of_local_servers server_log;
    	void raise_alarm(in VehicleEvent event);
    	void register_local_server(in LocalServers server);
    	Log_of_machines return_machines();
    };
};
