package ExitGate;


/**
* ExitGate/ExitGate.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exit.idl
* Thursday, 7 March 2019 12:20:31 o'clock GMT
*/

public interface ExitGate extends ExitGateOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ExitGate
